language: ruby
sudo: false
cache: bundler
rvm:
  - 2.4.1
  - 2.3.4
  - 2.2.7
  - jruby
bundler_args: ''
gemfile:
  - gemfiles/rails3.2.gemfile
  - gemfiles/rails4.1.gemfile
  - gemfiles/rails4.2.gemfile
  - gemfiles/rails5.0.gemfile
  - gemfiles/rails5.1.gemfile
matrix:
  exclude:
  - rvm: jruby
    gemfile: gemfiles/rails5.0.gemfile
  - rvm: jruby
    gemfile: gemfiles/rails5.1.gemfile
branches:
  only: [master]
