language: ruby
sudo: false
cache: bundler
rvm:
  - 2.4
  - 2.3
  - 2.2
  - jruby-9.1.15.0
bundler_args: ''
gemfile:
  - gemfiles/rails3.2.gemfile
  - gemfiles/rails4.2.gemfile
  - gemfiles/rails5.0.gemfile
  - gemfiles/rails5.1.gemfile
  - gemfiles/rails5.2.gemfile
branches:
  only: [master]
