language: ruby
sudo: false
cache: bundler
install:
  bundle install
rvm:
  - 2.4.1
  - 2.3.4
  - 2.2.7
  - jruby
gemfile:
  - gemfiles/rails3.2.gemfile
  - gemfiles/rails4.1.gemfile
  - gemfiles/rails4.2.gemfile
  - gemfiles/rails5.0.gemfile
matrix:
  exclude:
  - rvm: jruby
    gemfile: gemfiles/rails5.0.gemfile
branches:
  only: [master]
