language: ruby
sudo: false
cache: bundler
rvm:
  - 2.2.2
  - 2.1.6
  - 2.0.0
  - jruby
gemfile:
  - gemfiles/rails3.2.gemfile
  - gemfiles/rails4.1.gemfile
  - gemfiles/rails4.2.gemfile
branches:
  only: [master]
